token: your discord token here
# enter your ip if you host this self bot in hosting service 
# keep it default if you host in your local computer
ip: default
web_password: admin
rpc_config:
  delay: 3.0
  data:
  - type: Spotify
    title: 𓆩♡𓆪 𝑷𝒉𝒂𝒎 𝑻𝒖𝒂𝒏 𝑯𝒂𝒊 𓆩♡𓆪
    large_img: https://i.ibb.co/xSFD6GQv/image.png
    small_img: https://media.tenor.com/uvC1Vj7ooUUAAAAC/cat-not-mine.gif
    delay: 3.0
    artist: 「🌡️{temp:c}°C」✧「🍃{wind:kph} km/h」
    album: '✧ ⏱️ Uptime: {uptime:days}d {uptime:hours}h {uptime:minutes}m {uptime:seconds}s
      ✧'
    duration: 6736
    elapsed: 3667
  - type: Youtube
    title: 📡{ping}ms ✧ {emoji:time} {temp:c}°C
    large_img: https://i.ibb.co/xSFD6GQv/image.png
    small_img: https://media.tenor.com/uvC1Vj7ooUUAAAAC/cat-not-mine.gif
    delay: 3.0
    line3: 𓆩♡𓆪 𝑷𝒉𝒂𝒎 𝑻𝒖𝒂𝒏 𝑯𝒂𝒊 𓆩♡𓆪
  - type: Twitch
    title: ⏱️{hour}:{min} | 📅{date}/{month}/{year}
    large_img: https://i.ibb.co/xSFD6GQv/image.png
    small_img: https://media.tenor.com/uvC1Vj7ooUUAAAAC/cat-not-mine.gif
    delay: 3.0
    line2: 💻 CPU: {cpu:usage}% ┊ 🧠 RAM: {ram:usage}%
    line3: 𓆩♡𓆪 𝑷𝒉𝒂𝒎 𝑻𝒖𝒂𝒏 𝑯𝒂𝒊 𓆩♡𓆪
giveaway_joiner:
  enabled: false
  logging: true
voice_config:
  enabled: false
  guild_id: '1380172194264518796'
  channel_id: '1490011142247026849'
auto_quest:
  enabled: true
  logging: true
  check_interval: 3600
webhook_logging:
  enabled: true
  webhook_url: weebhook here